#ifndef COLOR_HPP
# define COLOR_HPP

# define Color_CG_Blue              0x007aa5
# define Color_CG_Red               0xe03c31
# define Color_Cadet                0x536872
# define Color_Cadet_Blue           0x5f9ea0
# define Color_Cadet_Grey           0x91a3b0
# define Color_Cadmium_Green        0x006b3c
# define Color_Cadmium_Orange       0xed872d
# define Color_Cadmium_Red          0xe30022
# define Color_Cadmium_Yellow       0xfff600
# define Color_French_Beige         0xa67b5b
# define Color_Cafe_Noir            0x4b3621
# define Color_Cal_Poly_Green       0x1e4d2b
# define Color_Cambridge_Blue       0xa3c1ad
# define Color_Desert               0xc19a6b
# define Color_Cameo_Pink           0xefbbcc
# define Color_Camouflage_Green     0x78866b
# define Color_Canary_Yellow        0xffef00
# define Color_Candy_Apple_Red      0xff0800
# define Color_Candy_Pink           0xe4717a
# define Color_Deep_Sky_Blue        0x00bfff
# define Color_Caput_Mortuum        0x592720
# define Color_Cardinal             0xc41e3a
# define Color_Caribbean_Green      0x00cc99
# define Color_Carmine              0x960018
# define Color_Rich_Carmine         0xd70040
# define Color_Carmine_Pink         0xeb4c42
# define Color_Carmine_Red          0xff0038
# define Color_Carnation_Pink       0xffa6c9
# define Color_Cornell_Red          0xb31b1b
# define Color_Carolina_Blue        0x99badd
# define Color_Carrot_Orange        0xed9121
# define Color_Castleton_Green      0x00563f
# define Color_Catalina_Blue        0x062a78
# define Color_Catawba              0x703642
# define Color_Cedar_Chest          0xc95a49
# define Color_Ceil                 0x92a1cf
# define Color_Celadon              0xace1af
# define Color_Celadon_Blue         0x007ba7
# define Color_Celadon_Green        0x2f847c
# define Color_Italian_Sky_Blue     0xb2ffff
# define Color_Celestial_Blue       0x4997d0
# define Color_Cherry               0xde3163
# define Color_Cerise_Pink          0xec3b83
# define Color_Cerulean_Blue        0x2a52be
# define Color_Cerulean_Frost       0x6d9bc3
# define Color_Chamoisee            0xa0785a
# define Color_Champagne            0xf7e7ce
# define Color_Charcoal             0x36454f
# define Color_Charleston_Green     0x232b2b
# define Color_Charm_Pink           0xe68fac
# define Color_Chartreuse           0xdfff00
# define Color_Web_Chartreuse       0x7fff00
# define Color_Cherry_Blossom_Pink  0xffb7c5
# define Color_Indian_Red           0xcd5c5c
# define Color_China_Pink           0xde6fa1
# define Color_China_Rose           0xa8516e
# define Color_Chinese_Red          0xaa381e
# define Color_Chinese_Violet       0x856088
# define Color_Chocolate            0x7b3f00
# define Color_Cocoa_Brown          0xd2691e
# define Color_Chrome_Yellow        0xffa700
# define Color_Cinereous            0x98817b
# define Color_Cinnabar             0xe34234
# define Color_Citrine              0xe4d00a
# define Color_Citron               0x9fa91f
# define Color_Claret               0x7f1734
# define Color_Classic_Rose         0xfbcce7
# define Color_Cobalt               0x0047ab
# define Color_Coca_cola_Red        0xfe001a
# define Color_Coconut              0x965a3e
# define Color_Coffee               0x6f4e37
# define Color_Columbia_Blue        0x9bddff
# define Color_Cool_Black           0x002e63
# define Color_Cool_Grey            0x8c92ac
# define Color_Copper               0xb87333
# define Color_Pale_Copper          0xda8a67
# define Color_Copper_Penny         0xad6f69
# define Color_Copper_Red           0xcb6d51
# define Color_Copper_Rose          0x996666
# define Color_Coquelicot           0xff3800
# define Color_Coral                0xff7f50
# define Color_Congo_Pink           0xf88379
# define Color_Coral_Red            0xff4040
# define Color_Cordovan             0x893f45
# define Color_Corn_Maize           0xfbec5d
# define Color_Cornflower_Blue      0x6495ed
# define Color_Cornsilk             0xfff8dc
# define Color_Cosmic_Latte         0xfff8e7
# define Color_Cotton_Candy         0xffbcd9
# define Color_Cream                0xfffdd0
# define Color_Crimson              0xdc143c
# define Color_Crimson_Glory        0xbe0032
# define Color_Electric_Cyan        0x00ffff
# define Color_Cyan                 0x00b7eb
# define Color_Cyber_Grape          0x58427c
# define Color_Cyber_Yellow         0xffd300

#endif